### ISSUE TITLE
ERROR: Gradle DSL method not found: 'implementation()'

### ISSUE THREAD

**Issue by bafu** [textileio/android-textile#53]
Followed the steps in the Install section of README (modifications of `build.gradle` are available [here](https://paste.ubuntu.com/p/dJqtPMNm8Z/)), but failed to build the project:

```
$ ./gradlew assembleDebug
...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/debug/codes/textile/android-textile/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'android-textile'.
> Could not find method implementation() for arguments [io.textile:textile:1.1.0] on object of type org.gradle.api.internal.artifacts.ds$.dependencies.DefaultDependencyHandler.
...
```

Changed `1.1.0` to `2.0.5` will get the same error.

---
**Environment**

* android-textile: 2.0.5 (commit `6771506`)
* Android Studio: 3.4.2
* Gradle: 5.1.1 (indicated in `gradle/wrapper/gradle-wrapper.properties`)
* Gradle plugin: 3.4.1 (indicated in `manifest.gradle`)

**Comment by asutula** [comment]
I haven't been able to reproduce this using the same environment as you. I did run into two other issues, I'm not sure if they would impact what you're experiencing:

1. I had to update to `minSdkVersion 24` in `app/build.gradle` to be compatible with Textile 2.0.5
2. I had to add the following compile options to `app/build.gradle` in the `android` section:

```
compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
}
```

Can you share your build.gradle files?

**Comment by bafu** [comment]
Thanks for your information and and my `build.gradle` is available [here](https://paste.ubuntu.com/p/RwCkTJwB9F/).

My `app/build.gradle` is [the one](https://github.com/textileio/android-textile/blob/master/app/build.gradle) in current master branch including:

```
    defaultConfig {
        ...
        minSdkVersion minSdk    // minSdk is 24 in manifest.gradle
        ...
    }
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by asutula** [comment]
Side note... I just updated to Android Studio 3.4.2, default new project configuration, and no problems getting Textile integrated aside from the two tasks I mentioned in my previous comment.

I see a couple of potential problems with the config files you sent.

The most problematic is that you're using a `project()` dependency for Textile:
```
implementation project('io.textile:textile:2.0.5')
```

That is wrong. You should use:

```
implementation 'io.textile:textile:2.0.5'
```

Possibly less problematic is that you're defining the Textile dependency in your top level `build.gradle`... App dependencies should go in your `app` module's `build.gradle`.

I'm a little confused about your link to `android-textile`'s `build.gradle` when referencing your `app/build.gradle`. Your app should have it's own `app/build.gradle` that included the dependency on Textile.

**Comment by bafu** [comment]
@asutula Thanks for the helpful tips. The root cause is that I added the Textile dependency in `<project-root>/build.gradle` instead of `<project-root>/app/build.gradle`.

I can build the app successfully by applying the modifications below:

```
diff --git a/app/build.gradle b/app/build.gradle
index 881f1d9..2ade019 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -73,4 +73,6 @@ dependencies {
 
     // Espresso dependencies (maybe needed in the future)
     // androidTestImplementation "androidx.test.espresso:espresso-core:$androidxTestEspressoVersion"
+
+    implementation 'io.textile:textile:2.0.5'
 }
diff --git a/build.gradle b/build.gradle
index 6f27426..5c6c134 100644
--- a/build.gradle
+++ b/build.gradle
@@ -16,9 +16,8 @@ allprojects {
     repositories {
         google()
         jcenter()
-        maven {
-            url 'https://jitpack.io'
-        }
+        maven { url "https://dl.bintray.com/textile/maven" }
+        maven { url 'https://jitpack.io' }
     }
 }
 
```

**Comment by asutula** [comment]
Glad to hear it :)
